---
name: Práctica Inversibilidad
locale: es
type: practice
beta: false
teacher_info: ''
language: prolog
id_format: "%05d"
order:
- 20
- 30
- 10
- 1
- 40
- 71
- 2
- 60
- 70
- 50
- 3
- 72
- 73
- 74
- 75
- 76
private: false
